name: Docker Pull from DockerHub workflow

on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string

jobs:
  docker-pull:
    runs-on: ubuntu-latest

    steps:
    - name: Docker pull
      run: docker pull ${{ inputs.image }}

    - name: Docker save
      run: docker save ${{ inputs.image }} > docker-image.tar
