name: Docker-Save-Artifact
run-name: Download for ${{ inputs.image }}

on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string

jobs:
  save:
    runs-on: ubuntu-latest
    steps:

      - name: Pull & save image
        run: |
          docker pull ${{ inputs.image }}
          docker save ${{ inputs.image }} | gzip > docker-image.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-tar
          path: docker-image.tar.gz
          retention-days: 15   # 默认 90 天，可选 1-90
